Repository joshua1535/Guanaquito-Events, pull requests merged in 2024-07, with the labels that each got.

#17 Feature/new database script
  Data/Database Script.sql
Labels: BD, Backend

#18 Adding database models modifications, new entity and dependencies
  Server/build.gradle
  Server/src/main/java/com/guanacobusiness/event_ticket_sales/models/entities/Event.java
  Server/src/main/java/com/guanacobusiness/event_ticket_sales/models/entities/EventLocation.java
  Server/src/main/resources/application.properties
Labels: BD, Backend

#20 Feat: Dependencies for Leafleat and Map component
  Client/package-lock.json
  Client/package.json
  Client/src/API/Instance.js
  Client/src/Components/MapComponent.jsx
  Client/src/pages/Create Event/CreateEvent.jsx
Labels: Frontend

#19 Feat/events hitory
  Server/.gitignore
  Server/.vscode/launch.json
  Server/src/main/java/com/guanacobusiness/event_ticket_sales/controllers/UserController.java
  Server/src/main/java/com/guanacobusiness/event_ticket_sales/repositories/RegisterRepository.java
  Server/src/main/java/com/guanacobusiness/event_ticket_sales/services/EventService.java
  Server/src/main/java/com/guanacobusiness/event_ticket_sales/services/RegisterService.java
  Server/src/main/java/com/guanacobusiness/event_ticket_sales/services/implementations/RegisterServiceImpl.java
  Server/src/main/java/com/guanacobusiness/event_ticket_sales/services/implementations/UserServiceImpl.java
  Server/src/main/resources/application.properties
Labels: Backend

#25 Adding Repository, Service and Controller of EventLocation
  Server/src/main/java/com/guanacobusiness/event_ticket_sales/controllers/EventLocationController.java
  Server/src/main/java/com/guanacobusiness/event_ticket_sales/models/dtos/EventLocationDTO.java
  Server/src/main/java/com/guanacobusiness/event_ticket_sales/repositories/EventLocationRepository.java
  Server/src/main/java/com/guanacobusiness/event_ticket_sales/services/EventLocationService.java
  Server/src/main/java/com/guanacobusiness/event_ticket_sales/services/implementations/EventLocationServiceImpl.java
  Server/src/main/resources/application.properties
Labels: Backend

#38 Feature/event recommend
  Server/src/main/java/com/guanacobusiness/event_ticket_sales/controllers/EventController.java
  Server/src/main/java/com/guanacobusiness/event_ticket_sales/repositories/CategoryRepository.java
  Server/src/main/java/com/guanacobusiness/event_ticket_sales/repositories/EventRepository.java
  Server/src/main/java/com/guanacobusiness/event_ticket_sales/services/CategoryService.java
  Server/src/main/java/com/guanacobusiness/event_ticket_sales/services/EventService.java
  Server/src/main/java/com/guanacobusiness/event_ticket_sales/services/implementations/CategoryServiceImpl.java
  Server/src/main/java/com/guanacobusiness/event_ticket_sales/services/implementations/EventServiceImpl.java
Labels: Backend

#37 Update: DB Script
  Data/Database Script.sql
  Data/Default Data.sql
Labels: enhancement, BD

#40 Refactor/event dto
  Server/src/main/java/com/guanacobusiness/event_ticket_sales/controllers/EventController.java
  Server/src/main/java/com/guanacobusiness/event_ticket_sales/controllers/UserController.java
Labels: Backend

#41 Creación de eventos con ubicación
  Client/package-lock.json
  Client/package.json
  Client/src/API/Instance.js
  Client/src/App.jsx
  Client/src/Components/MapComponent.jsx
  Client/src/Services/eventLocationService.js
  Client/src/pages/Create Event/CreateEvent.jsx
  Client/src/pages/Create Event/CreateEvent.module.css
  Server/src/main/resources/application.properties
Labels: Frontend

#44 Feature/departments model
  Data/Database Script.sql
  Data/Default Data.sql
  Server/src/main/java/com/guanacobusiness/event_ticket_sales/controllers/DepartmentController.java
  Server/src/main/java/com/guanacobusiness/event_ticket_sales/controllers/EventLocationController.java
  Server/src/main/java/com/guanacobusiness/event_ticket_sales/models/dtos/DepartmentDTO.java
  Server/src/main/java/com/guanacobusiness/event_ticket_sales/models/dtos/EventLocationDTO.java
  Server/src/main/java/com/guanacobusiness/event_ticket_sales/models/dtos/FormatedDepartmentDTO.java
  Server/src/main/java/com/guanacobusiness/event_ticket_sales/models/entities/Department.java
  Server/src/main/java/com/guanacobusiness/event_ticket_sales/models/entities/EventLocation.java
  Server/src/main/java/com/guanacobusiness/event_ticket_sales/repositories/DepartmentRepository.java
  Server/src/main/java/com/guanacobusiness/event_ticket_sales/repositories/EventLocationRepository.java
  Server/src/main/java/com/guanacobusiness/event_ticket_sales/services/DepartmentService.java
  Server/src/main/java/com/guanacobusiness/event_ticket_sales/services/EventLocationService.java
  Server/src/main/java/com/guanacobusiness/event_ticket_sales/services/implementations/DepartmentServiceImpl.java
  Server/src/main/java/com/guanacobusiness/event_ticket_sales/services/implementations/EventLocationServiceImpl.java
  Server/src/main/java/com/guanacobusiness/event_ticket_sales/utils/DepartmentMapper.java
  Server/src/main/java/com/guanacobusiness/event_ticket_sales/utils/EventLocationMapper.java
  Server/src/main/java/com/guanacobusiness/event_ticket_sales/utils/EventMapper.java
Labels: bug, BD, Backend

#45 Feature/tier price recomendation
  Server/src/main/java/com/guanacobusiness/event_ticket_sales/controllers/TierController.java
  Server/src/main/java/com/guanacobusiness/event_ticket_sales/models/dtos/RecommendedTierDTO.java
  Server/src/main/java/com/guanacobusiness/event_ticket_sales/services/TierService.java
  Server/src/main/java/com/guanacobusiness/event_ticket_sales/services/implementations/TierServiceImpl.java
Labels: enhancement, Backend

#47 Fixing some issues on EventsPage and HomePage, adding categoryservice…
  Client/src/Services/categoryservice.js
  Client/src/pages/Create Event/CreateEvent.jsx
  Client/src/pages/EventsPage/EventsPage.jsx
  Client/src/pages/HomePage/HomePage.jsx
  Server/src/main/resources/application.properties
Labels: bug, Frontend

#48 Integración diseño de recomendacion de precios
  Client/src/pages/Add Tiers/AddTiers.jsx
  Client/src/pages/Add Tiers/AddTiers.module.css
Labels: Frontend

#49 Bug fix/event recommendation
  Server/src/main/java/com/guanacobusiness/event_ticket_sales/repositories/CategoryRepository.java
Labels: Backend

#51 Feature/events map view
  Client/src/Services/eventService.js
  Client/src/pages/Create Event/CreateEvent.jsx
  Client/src/pages/EventsPage/EventsPage.jsx
  Client/src/pages/EventsPage/EventsPage.module.css
Labels: Frontend

#50 Add: Integration Demo
  Client/package-lock.json
  Client/src/pages/BuyTicketPage/BuyTicketPage.jsx
  Client/src/pages/Create Event/CreateEvent.jsx
  Client/src/pages/EventsPage/EventsPage.jsx
  Client/src/pages/EventsPage/EventsPage.module.css
Labels: bug, Frontend

#52 Adding Tier Recommendations functionality on Add Tiers to event page
  Client/src/App.jsx
  Client/src/Services/tierService.js
  Client/src/pages/Add Tiers/AddTiers.jsx
  Client/src/pages/Admin Events/AdminEvents.jsx
  Client/src/pages/Event Permits/EventPermits.jsx
  Client/src/pages/Event Permits/EventPermits.module.css
  Client/src/pages/HomePage/HomePage.jsx
  Client/vite.config.js
Labels: Frontend

#55 Fixing demo issues
  Client/src/pages/BuyTicketPage/BuyTicketPage.jsx
  Client/src/pages/EventsPage/EventsPage.jsx
Labels: bug, Frontend

#57 El Select no mostraba la selección actual
  Client/src/pages/Create Event/CreateEvent.jsx
  Client/src/pages/Modify Event/ModifyEvent.jsx
Labels: bug, Frontend

#59 Hotfix/missing code
  Client/src/pages/EventsPage/EventsPage.jsx
Labels: bug, Frontend

#61 Fixing some issues on event page
  Client/src/pages/EventsPage/EventsPage.jsx
Labels: bug, Frontend

#62 Adding weather forecast display on event details using OpenWeather AP…
  Client/.gitignore
  Client/src/pages/BuyTicketPage/BuyTicketPage.jsx
Labels: Frontend

#63 Document
  Data/Database_Script.sql
  Data/Default_Data.sql
  Data/diagrama.png
  Documents/ScanCode.png
  README.md
Labels: documentation

#65 Fixin design issues
  Client/src/pages/BuyTicketPage/BuyTicketPage.jsx
  Client/src/pages/BuyTicketPage/BuyTicketPage.module.css
  Client/src/pages/EventsPage/EventsPage.jsx
  Client/src/pages/EventsPage/EventsPage.module.css
  Client/src/pages/HomePage/HomePage.jsx
  Client/src/pages/HomePage/HomePage.module.css
Labels: bug, Frontend
